### ISSUE TITLE
User without Lock Permission Can Create Locks with no Own

### ISSUE THREAD

**Issue by Hayden2006** [connection-lost/LockettePro#10]
I use the permission nodes which don't allow use of this plugin until a certain rank. Rank2 is when players can lock stuff on my server, and Rank3 is when they can start editing their Lockette signs. When a player who is not yet in the correct rank (Rank0-Rank1) and does not have the permissions to lock anything, when they try to lock something, the result is a lock which nobody except an Admin can open or break. The [private] tag on the first line remains while the other 3 lines are blank, essentially locking a chest or door for nobody. It's impossible to stop players from trying to lock things before they are in the correct rank, so this bug is a real hassle.

**Comment by connection-lost** [comment]
Thanks for reporting this, it is confirmed, I will look for a fix.

(I am on vacation sorry if I do this too slow :( )

**Comment by Hayden2006** [comment]
No rush, sorry I'm finding so many issues while you are trying to enjoy yourself  :p
