### ISSUE TITLE
Everyone not working when UUID is enabled

### ISSUE THREAD

**Issue by phoenixlzx** [connection-lost/LockettePro#18]
Player who create an `[Everyone]` sign automatically add the player name and uuid to the second line, so only the player could break or lock the block/chest.

**Comment by connection-lost** [comment]
This is not how Lockette/LockettePro currently work... Currently [Everyone] sign works as a user line.

**Comment by phoenixlzx** [comment]
Then that's the problem. We tried adding `[Everyone]` to the user line, and someone right click on the sign, the `[Everyone]` becomes that user and the chest is locked.

**Comment by connection-lost** [comment]
Admins and only admins can edit the owner of the sign (the line directly under [Private]). The plugin will also always trust an admin's action. 
Maybe I didn't understand what you said, can you specify how to reproduce it?

**Comment by phoenixlzx** [comment]
For what my players tested:

Create a `[More Users]` sign, right click it and set line 2 as `[Everyone]`
right click on the sign, the second line becomes the player's name.

I don't know if they tried on a `[Private]` sign, will do more tests on this.

**Comment by phoenixlzx** [comment]
My fault, not make it clear for players. `[Everyone]` should be at line 3 or 4.

Closing issue, thanks.

**Comment by phoenixlzx** [comment]
Not OK... Thanks to @cyilin for testing.

When UUID is enabled, `[Everyone]` will be updated on right click on the sign.

**Comment by hrl** [comment]
To reproduce it:  
a) only one sign  
```text
[Private]
some_player
[Everyone]
```
b) multiple signs
```text
[Private]
some_player
```
```text
[More Users]
[Everyone]
```
`[Everyone]` will be replaced with the player's id, when the player using the locked chest/door, if he's not on the sign.

**Comment by connection-lost** [comment]
That makes sense, this is now a bug. Thanks for figuring things out :)
