### ISSUE TITLE
Can not support 1.7.10? 不支持 1.7.10 吗？

### ISSUE THREAD

**Issue by sourcepowered** [connection-lost/LockettePro#19]
Sorry for my bad Chinese:
请问该插件不支持1.7.10吗？经过我的测试我发现1.7.10的确存在很多问题，我使用的是Thermos服务端。感谢您提供这么优秀的插件和给我的答复！
如果不支持1.7.10，那能否让其支持呢？因为现在还有很多的开服的朋友使用1.7.10版本呢。

`能用中文交流真是太好了，英文越发无法让我表达清除我说的话的意思，我越来越感觉英文的26个字母与中文的几万亿方块字是无法相比的。中文是一门博大精深的语言。`

**Comment by connection-lost** [comment]
I do have an alternative version for 1.6~1.7, which I will leave it here:
https://github.com/connection-lost/LockettePro/releases/tag/v1.9.4
