### ISSUE TITLE
Permission Group support

### ISSUE THREAD

**Issue by WouterDM** [connection-lost/LockettePro#20]
Just like in the original Lockette, group support for permission plugins would be nice. That way we can lock doors to a specific group. See original Lockette discussion.

> Additionally, you can enter [Everyone] on lines 3 or 4 instead of a user name to allow everyone access to the contents of a private container, or [Operators] to allow ops access. If a Permissions plugin is available, you can use groups like [Moderator] or [Admins] or others as defined in the Permissions settings files.
https://bukkit.org/threads/sec-lockette-simple-chest-and-door-lock-no-databases-moved-to-bukkitdev.4336/

**Comment by connection-lost** [comment]
This feature is now added :)
Expect a release soon
