### ISSUE TITLE
Support for PlotSquared and aSkyBlock - 添加对pltosquared和askyblock插件的支持

### ISSUE THREAD

**Issue by xyblues** [connection-lost/LockettePro#21]
使用plotsquared地皮插件时
当我给予他人use 开门权限
但是不给予放置权限时
玩家依然能锁住他人的门
请添加对plotsquared支持 谢谢了
askyblock 插件也是同理...

**Comment by connection-lost** [comment]
- [x] aSkyBlock
- [ ] PlotSquared

**Comment by connection-lost** [comment]
Release soon, testing
