### ISSUE TITLE
Feature Request: Get [Private] name automatically

### ISSUE THREAD

**Issue by UnioDex** [connection-lost/LockettePro#23]
Request: On a player write to sign's first line [Private] and click done, plugin will automatically set second line his name. 

Why i want this:
Players can forget writing their name to sign when first line is [Private] and second line is [Timer:@].

**Comment by connection-lost** [comment]
This is intended as players can lock chests for others

**Comment by Oruss7** [comment]
may be, set current player name if second line is empty ?

**Comment by connection-lost** [comment]
@Oruss7 The second line will always be the player's name regardless what he writes, unless he has "lockettepro.lockothers" permission. This design is intentional, because It is possible for a player to type his name wrong, therefore cause a deadlock situation.
