### ISSUE TITLE
最新版的LockettePro和Plotsquared插件依然有点问题

### ISSUE THREAD

**Issue by xyblues** [connection-lost/LockettePro#25]
如图 成员XYBlues 是可以锁箱子的
但是 可信成员XYBlues1 无法锁上箱子
我需要让可信成员也能锁上箱子
给予成员的指令为/p add 玩家
给予可信成员的指令为/p trust 玩家
![pd 0_ 4fk 5 nv jkcjyl6n](https://cloud.githubusercontent.com/assets/15712089/17652835/35759e20-62ba-11e6-9bfd-63d1f4f59d4a.png)

**Comment by connection-lost** [comment]
Fixed
已修复
