### ISSUE TITLE
Bug LockettePro

### ISSUE THREAD

**Issue by NelsonHD** [connection-lost/LockettePro#29]
Chinese ver : LockettePro 铁门有一个BUG，如果在别人空岛( ASkyBlock )可以锁别人的铁门
即使权限有锁

English ver: LockettePro can lock other player island ( ASkyblock ) 's iron door which locked the permission

**Comment by connection-lost** [comment]
Cannot reproduce. Make sure you are on the latest version because old version does not support ASkyBlock.
