### ISSUE TITLE
Admin can not edit other players' sign after transfered from the original Lockette

### ISSUE THREAD

**Issue by k-jiang** [connection-lost/LockettePro#30]
Tested on:
Spigot 1.11 build 1101
LockettePro 2.6.4

(English)
Admin/moderators are unable to right click on other player's signs even with permission lockettepro.admin.edit. So there is no way for editing those. Such an issue occurred with the previous lock signs after I have replaced Lockette with LockettePro. There is no exception from the console while testing.
And this problem seems happened with all the signs created, especially after server restarted, even after LockettePro have been installed.
Yet I have no problem with Ops.

Please consider fix it since LockettePro is a great plugin and I don't want to give it up.

Thank you!

ps: if you want any further tests please feel free to ask me. I'm very happy to help.

(Chinese)
即使设定了lockettepro.admin.edit权限，我的管理员仍然无法右键点选其他玩家创建的牌子锁，所以管理员也无法编辑玩家的牌子锁。这个问题是在我更换Lockette插件为LockettePro之后发现的。右键牌子时后台没有任何报错。
这个问题貌似不仅针对原来由Lockette创建的牌子，即使是更新到LockettePro后新创建的牌子也存在同样的问题，特别是在服务器重启后。
然而OP并没有遇到这个问题。
请修复这个问题。LockettePro是个很好的插件，我不想把它换掉。

谢谢！
ps: 如果你需要人测试欢迎随时联系，我很乐意提供帮助。

**Comment by connection-lost** [comment]
Hi, unfortunately I cannot conclude anything right now. I personally use LockettePro on my server and there is no problem with it. 

First question, can OP player edit signs on your server?

If they still cannot edit it, please provide:
1. LockettePro's config file
2. List of other plugin that you are using

**Comment by k-jiang** [comment]
My OPs can edit signs on my server with no issue.

After several further tests, I found out that this problem only occurs after I have restarted my server. So maybe you need to restart yours as well.

One more thing: the problem is not just editing, but selecting a sign also. All of my moderators cannot select other players' signs even with proper permissions associated with. Unless I Opped them, there is no way for them to select and edit any signs which do not belong to them.

Here is what my config.yml looks like:

> \# Configuration file
> \# https://github.com/connection-lost/LockettePro/wiki/*-config.yml
> \# If there are missing entries, you can add them manually.
> 
> language-file-name: lang_zh-cn.yml
> 
> enable-quick-protect: true
> enable-uuid-support: true
> block-interfere-placement: true
> block-item-transfer-in: false
> block-item-transfer-out: true
> block-hopper-minecart: remove
> cache-time-seconds: 0
> private-signs:
> - '[私有]'
> - 【私有】
> - '[锁]'
> - 【锁】
> - '[Private]'
> - '[private]'
> additional-signs:
> - '[多人]'
> - 【多人】
> - '[更多人]'
> - 【更多人】
> - '[更多]'
> - 【更多】
> - '[多用户]'
> - 【多用户】
> - '[More Users]'
> - '[more users]'
> - '[More]'
> - '[more]'
> - '[More People]'
> - '[more people]'
> everyone-signs:
> - '[公用]'
> - 【公用】
> - '[公共]'
> - 【公共】
> - '[公开]'
> - 【公开】
> - '[所有人]'
> - 【所有人】
> - '[Everyone]'
> - '[everyone]'
> timer-signs:
> - '[计时器:@]'
> - 【计时器:@】
> - '[计时:@]'
> - 【计时:@】
> - '[定时:@]'
> - 【定时:@】
> - '[Timer:@]'
> - '[timer:@]'
> lockables:
> - CHEST
> - TRAPPED_CHEST
> - FURNACE
> - BURNING_FURNACE
> - HOPPER
> - BREWING_STAND
> - DIAMOND_BLOCK
> - WOODEN_DOOR
> - SPRUCE_DOOR
> - BIRCH_DOOR
> - JUNGLE_DOOR
> - ACACIA_DOOR
> - DARK_OAK_DOOR
> - IRON_DOOR_BLOCK
> - FENCE_GATE
> - SPRUCE_FENCE_GATE
> - BIRCH_FENCE_GATE
> - JUNGLE_FENCE_GATE
> - DARK_OAK_FENCE_GATE
> - ACACIA_FENCE_GATE
> protection-exempt:
> - nothing
>

**Comment by connection-lost** [comment]
You mentioned that you "this problem only occurs after I have restarted my server", can you elaborate? Can you make this issue go away somehow?

**Comment by k-jiang** [comment]
Ok, lets me make it clear:

- Problem description:
Admin can not select other player's lock sign by clicking on it after server restarted.

- To duplicate this problem, you will need:
1. A player creates a lock sign on a chest.
2. Restart(reboot) the Spigot server.
3. An admin or moderator with the permission "lockettepro.admin.edit" can not select the sign by clicking. So there is no way for admin or moderator to edit/modify this sign either.

Note that after step 1, the admin/moderator is somehow able to click and select the sign before server restarted. So you need to restart your test server in order to duplicate this problem.

(If you have any more question, please feel free to ask.)

**Comment by connection-lost** [comment]
I have identified the bug. I had a typo in the plugin. 

Before I release the fix, use "lockettepro.edit.admin" instead of "lockettepro.admin.edit" for now.

**Comment by k-jiang** [comment]
So if that the case... why my admin can edit other player's sign in the first place (before server restart and without proper permission)?

I guess there is another bug which makes lock signs vulnerable from editing by anyone. So you may have to check your code more carefully.

**Comment by k-jiang** [comment]
Just a reminder: the typo is still not been fixed in version 2.7.0. #30
