### ISSUE TITLE
Can't find 3.0 download

### ISSUE THREAD

**Issue by AeSix** [connection-lost/LockettePro#38]
Ok ok, I know you've probably not built it, definitely haven't released it.  But I need it.  Specifically, the sign expiry.  

It would also be nice if you could add these features:
1) Add configurable requirement that LockettePro signs be made only in the user's GriefPrevention area
2) Add config to allow signs to be removed by LP plugin when GP area expires / is removed by player
3) Add config option to allow Auto-extend expiry of signs in GP area (in case option 1 above is turned off)

I would be OK with the auto-expire part though.  Great plugin otherwise, just see a lot of abandoned locked chests that my players can't do anything with, even though the rest of the build can be dismantled and salvaged. Or even claimed. 

Any help and progress towards this end would be great!

Thank You :)

**Comment by connection-lost** [comment]
These are in the next version but I cannot give you any eta. I am currently overwhelmed by my lyfe.
