### ISSUE TITLE
odd warn exception

### ISSUE THREAD

**Issue by chillerkraft** [connection-lost/LockettePro#40]
09.06 03:12:19 [Server] WARN [LockettePro] Plugin LockettePro v2.7.0 generated an exception while executing task 84
09.06 03:12:19 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
09.06 03:12:19 [Server] INFO at org.mcstats.MetricsLite.postPlugin(MetricsLite.java:285) ~[?:?]
09.06 03:12:19 [Server] INFO at org.mcstats.MetricsLite.access$200(MetricsLite.java:51) ~[?:?]
09.06 03:12:19 [Server] INFO at org.mcstats.MetricsLite$1.run(MetricsLite.java:173) ~[?:?]
09.06 03:12:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[custom.jar:git-Spigot-3fb9445-6e3cec8]
09.06 03:12:19 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [custom.jar:git-Spigot-3fb9445-6e3cec8]
09.06 03:12:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
09.06 03:12:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
09.06 03:12:19 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by chillerkraft** [comment]
1.11.2 spigot

**Comment by connection-lost** [comment]
This is due to other plugin contains old metrics code. Since metric only get loaded once, the metric class of the first plugin who has it gets loaded, and the metric class gets called by the last plugin loaded.

**Comment by chillerkraft** [comment]
thanks man @connection-lost glad to see your active and helpful :) it was cclogger causing my problems. old metrics. yea like you said! thanks so much!

**Comment by connection-lost** [comment]
I will remove metrics for the next version, since mcstats has approx. 90% downtime.

**Comment by chillerkraft** [comment]
ok
can you tell me why [EVERYONE] signs don't work?
should i open a new issue?

**Comment by chillerkraft** [comment]
@connection-lost

**Comment by connection-lost** [comment]
[Everyone] is case sensitive.
