### ISSUE TITLE
1.12 Iron Doors

### ISSUE THREAD

**Issue by jonassm** [connection-lost/LockettePro#41]
Hi,

In 1.12, iron doors that have lockette signs do not open on right click. Does output noise.

No errors in logs

**Comment by haugsvar** [comment]
A can confirm this bug.

**Comment by connection-lost** [comment]
I will check this out today. But I have a feeling that this is not fixable.

**Comment by connection-lost** [comment]
Fixed in an earlier unreleased build, this is not a issue at this moment.
Please check Spigot release page later.

**Comment by haugsvar** [comment]
New release seems to work fine. Thank you.
