### ISSUE TITLE
1.12 Interacting with sign cause them to appear invisible

### ISSUE THREAD

**Issue by Trioxan** [connection-lost/LockettePro#42]
Hi, in 1.12, when placing a LockettePro sign or opening a chest that is protected, causes the sign to appear invisible to the user. 
![2017-06-12_18 23 42](https://user-images.githubusercontent.com/29381869/27046439-514a1bb0-4f9c-11e7-8194-5cf31b77add4.png)
![2017-06-12_18 25 10](https://user-images.githubusercontent.com/29381869/27046473-7adff544-4f9c-11e7-87fa-2fb80d2cfad5.png)

**Comment by connection-lost** [comment]
This is not a problem on my side. Testing with LockettePro plugin only works fine. 
If you are using other plugins there may be a conflict/incompatibility. I can help you identify this issue but you need to show me your plugin list.

**Comment by Trioxan** [comment]
This is the current plugin list i've got set up. 
![pluginlist](https://user-images.githubusercontent.com/29381869/27059955-a2dcc524-4fd1-11e7-9da2-02132ecb915b.png)

**Comment by Trioxan** [comment]
(EDIT) The issue only occurs when using the ProtocolLib Plugin when LockettePro's UUID support is true. Changing this to False, alleviates the issue.

**Comment by Pawned** [comment]
Can confirm this issue. Would appreciate if a fix could be made as I do want to continue using UUID support.

**Comment by connection-lost** [comment]
I will take care of this issue tonight.
