### ISSUE TITLE
using lockette with worldguard

### ISSUE THREAD

**Issue by Nekrose483** [connection-lost/LockettePro#44]
Hello. i have an issue with being able to lock chests in a worldguard'd region. 

 

steps to reproduce: install lockette and worldguard and worldedit. test that lockette works on a chest bydefault. then select and define a region with worldguard using a woodenaxe and /rg define xxxx. test lockette again with all default settings on everything. does not work, and i have all admin prermissions and op.

 

to go further, giving normal users rights to break and build blocks does not work either, even though they can place and take away the chest just fine and use it too. however placing a sign on the chest is greeted with "you cannot use lockette on this chest" and i don't know why. i've enabled all flags i could think of and it still doesn't work... and its not permissions because even i have all permissions and it still doesn't work. 

 

i've been looking around for hours for anything on this and not one single forum post about using worldguard and lockette together. only in worldguard's page it mentions to use lockette instead of its chest thing and here, says just to give players rights to break blocks. none of that helps.

 

minecraft version 1.11.2. worldguard 6.2 (the one that supports 1.11.2 because the lastest version does not and would not work.) and most recent version of lockette from this exact page.

 

is there any suggestions to try... or a known fix for to be able to use worldguard with lockette?

**Comment by connection-lost** [comment]
Sounds like worldguard support is broken? The symptom is, user cannot use the chest in a worldguard region regardless they have the permission?
I will look into that.

**Comment by Nekrose483** [comment]
thank you, and yes. that /was/ the symptom....

i have tried further looking into the issue from my perspective, having limited understanding of how the code itself is written, but i seem to have set higher priority for worldguard using the permissionsex which inturn made /me/ able to lock things again. which i believe inherently means its a permissions issue. so i granted all permissions of worldguard building to people so now they can build on their own land.. however, they cant use lockette on the land, but i can.. however, they can use lockette everywhere outside of the worldguard guarded city.

by default, lockette "just worked" when i installed it. forcing worldguard to look at permissionsex [which isn't default behaviour] seemed to work for the most part on fixing any other problems i might have had. but i wonder now if since worldguard is checking all permissions now, on guarded land, that its now enforcing the need for permissions from lockette to be assigned from default. i know that'd be a weird behaviour, but its the only thing i can think of other than the two just being incompatable. which is weird, because theres so much on using the two together. just nothing on this specific issue.

anyway, i've JUST NOW given default users the perms for lockette.user.create.* which, again, is something i didn't have to do by default. will have to wait for a non-op user to come into town, but i will say if this solved the issue or not.

**Comment by Nekrose483** [comment]
giving permissions did not work. i guess i was wrong in thinking that. however players have all rights to build/remove/use/destroy entities/breakstuff via worldguard on lockette it just says i need to give them the break permissions. well, they have that so i'm not sure what i'm doing wrong at this point.

**Comment by connection-lost** [comment]
Sorry I was not able to reproduce this issue. Here are the steps that I used, please tell me if I missed anything:
1. Player A has OP and player B is a normal player. Player B does not have any permission.
2. Player A defines an area "X" (/region define X). Player B cannot build inside, neither can he use any chests or lock them.
3. Player A give everyone build permission to region X (/region flag X build allow). B can now lock chest by either using quick lock or manual lock.
4. Revert step 3. Player A set player B as the owner of region X (/region addowner X B). B can now lock chest by either using quick lock or manual lock.

Tested on (LockettePro 2.8.1, MC 1.12, WorldGuard 6.21) and (LockettePro 2.8.0, MC 1.11.2, WorldGuard 6.1.3).

**Comment by connection-lost** [comment]
Enforcing LockettePro's permission on WorldGuard's land (or any guarded land) is mandatory. If not, a malicious player with interact access but without build access can place lock signs on the chest.

**Comment by connection-lost** [comment]
But I have a better idea. Most incompatibilities caused by things like this will be fixed if I do #47.

**Comment by Nekrose483** [comment]
ok. i'm going to try adding that flag you said. (i litterally added permissions from permissionsex. never actually added any flags to any regions.)

**Comment by connection-lost** [comment]
Can you tell me what exactly did you do? If possible can you answer like "/pex group xxx xxx" or paste some permission.yml content?

**Comment by Nekrose483** [comment]
on curses website it says version 2.4.1 is most updated build. how do i get this version 2.8.0?

edit: bukkit also gives me the same exact version which is 2.4.1

**Comment by connection-lost** [comment]
...
I haven't been update at bukkit side for a long time, try spigot: https://www.spigotmc.org/resources/lockettepro-uuid-support.20427/

**Comment by Nekrose483** [comment]
i assume now my version is out of date though, unless your 2.8.0 was a typo. i'm not sure how to give the latest version. if that's the case, then theres no issue, just a lack of me not being able to clearly find the files i need to

**Comment by Nekrose483** [comment]
alright, updated version is installed. i will have to wait for a player to come on an help me test if they can lock the chest, then i can close this issue and appologise for being dumb, as i thought both of those websites were the current version

**Comment by connection-lost** [comment]
Sorry for not updating Bukkit's page. I have put a link on BukkitDev to redirect to Spigot :(

**Comment by Nekrose483** [comment]
ok. did not work. steps to reproduce: have a world with worldguard 6.2 worldedit 6.1.5 and lockettepro 2.8.0.

player A is op. player B is normal.

/define region X [player A can lock chests, B cannot.]
set the owner of region to player B. [player A can lock chests and all that, player B can build and do everything except lock chests.]
set flag build to allow on region. [nothing changes]

**Comment by Nekrose483** [comment]
however, for your post: 

Can you tell me what exactly did you do? If possible can you answer like "/pex group xxx xxx" or paste some permission.yml content?

i will post some content.

this is what i did.
[selected region with wooden axe] /rg define X
/rg addowner B
/rg flag X build allow

pex-wise:
/pex user B group add default [player was added to default group]

default:
    options:
      default: 'true'
      rank: '1000'
    permissions:
    - lockette.user.create.* [permissions needed for your plugin]
    - worldguard.build.*      [default build permissions to build in regions you own]
    - essentials.rules
    - essentials.help            [rules and help.. build perms just thrown in there to make sure i have it covered]
    - essentials.build.*
    - modifyworld.*             [default "you need this to build anywhere in a pex enabled server" permissions.]
 Admin:
    permissions:
    - '*'
    - permissions.*


all messages in [] were obviously added after i pasted here and are not part of the permissions file.

**Comment by Nekrose483** [comment]
i gave someone permissions for lockettepro.* and worldguard.* and still nothing. so may be something with essentials or worldedit.

**Comment by connection-lost** [comment]
Sorry for late reply. Unfortunately I have something to do IRL recently so I cannot do a lot of updates in a few days.

**Comment by Nekrose483** [comment]
ok so after some testing, i found that specifically only OPed players are able to place signs in defined regions. i dont know why still though.

**Comment by Nekrose483** [comment]
well, i updated the server to 1.12 and it started working with out me changing anything except the spigot jar... leading me to believe it was an issue with the code itself and its interaction with that version of minecraft. the few other mods i have in all are tested and working. as i said, i changed nothing but everything works now. so, idk what to say. thanks for your help though.
