### ISSUE TITLE
Ender Crystal will damage the locked box

### ISSUE THREAD

**Issue by tygh78071388** [connection-lost/LockettePro#56]
Ender Crystal will damage the locked box
![image](https://user-images.githubusercontent.com/28720564/28265891-a07551d4-6b24-11e7-914d-1fa0c0a20b38.png)
![image](https://user-images.githubusercontent.com/28720564/28265897-a9a2f1a8-6b24-11e7-90be-f91abcc7c20f.png)

**Comment by connection-lost** [comment]
Will take a look at it after my vacation

**Comment by connection-lost** [comment]
I cannot replicate this issue. Please make sure you are on the latest version, downloaded from spigot. The protection-exempt entry in config.yml should not contain "explosion" as well.
