### ISSUE TITLE
[private] Problem

### ISSUE THREAD

**Issue by MatinHQ** [connection-lost/LockettePro#70]
When Some Of Players Or Me Want Use Private Chest's For Example [private] line 2 :Matin_Dark Change sign to error and say you can't lock that !

/lock debug 👍:
![image](https://user-images.githubusercontent.com/22664859/32406547-e24ecee8-c18f-11e7-9f65-05abcc70f34e.png)

**Comment by connection-lost** [comment]
Sorry but I didn't get that. Can you elaborate, like steps to reproduce?
Also, please also take a note if you are locking chests in skyblock regions, since only owners and authorized builders can lock them.

**Comment by MatinHQ** [comment]
Solved Thanks
