### ISSUE TITLE
Unlock option?

### ISSUE THREAD

**Issue by Kzitold** [connection-lost/LockettePro#71]
Any chance of a way to allow the lock owner to not lock a chest? Like a /unlock and it brings up the sign editor to be a regular sign.

I just want to be able to label my chests!

**Comment by connection-lost** [comment]
use "shift + place sign". For more information check out Wiki for ["enable-quick-protect" section](https://github.com/connection-lost/LockettePro/wiki/*-config.yml).

**Comment by Kzitold** [comment]
But how would I **not** lock a chest if quick-protect is set to "sneak?"

**Comment by connection-lost** [comment]
By "not sneaking".

**Comment by Kzitold** [comment]
Seems to just open the chest without sign placing on the public server I'm on.

Must be an old or modified version of the plugin.
