### ISSUE TITLE
Block interfere protection double chest bug

### ISSUE THREAD

**Issue by andris155** [connection-lost/LockettePro#74]
![2017-11-12_15 21 56](https://user-images.githubusercontent.com/8324198/32699894-40f95ae8-c7bd-11e7-8eb1-8fcb66977e2f.png)

**Comment by connection-lost** [comment]
Not sure what you mean, but "block interfere" means "you cannot place hopper which can potentially snap item from the chest".
Signs cannot be put "on" the chest only. It can still be put next to a chest.
