### ISSUE TITLE
"Signs" plugin can unlock door/chest

### ISSUE THREAD

**Issue by lindwurm** [connection-lost/LockettePro#76]
plugin: https://dev.bukkit.org/projects/signs
video: https://imgur.com/9Lj1vhs

1. lock door/chest with SIGN
2. edit SIGN with INK_SAC
3. SIGN show "[ERROR]" and LockettePro say **This block is already locked** , but there is unlocked door/chest.

**Comment by connection-lost** [comment]
This feature requires Signs plugin contributor to support LockettePro instead of letting LockettePro to support Signs.
I will try to find a workaround if there are multiple request regarding this issue and Signs plugin contributor refuse to fix the issue.
