### ISSUE TITLE
Timer doesn't work

### ISSUE THREAD

**Issue by Hayden2006** [connection-lost/LockettePro#8]
I'm using Bukkit 1.9.2 and the newest LockettePro plugin version. and the timer function does not work on single or double doors **if the sign is used on a bottom block (to hide it)**. This is true for iron and wooden doors and also for locked doors which were locked with the original Lockette plugin.

**Comment by connection-lost** [comment]
Confirmed, thanks for reporting.
Will fix :)

**Comment by Hayden2006** [comment]
no problem, how do I request features? do I do that the same way as this?

**Comment by connection-lost** [comment]
Yea, you can just create a(nother) issue as feature request
Keep in mind don't expect all feature requested will be accepted :)

**Comment by connection-lost** [comment]
So this one is fixed. It is caused by a typo :(

**Comment by Hayden2006** [comment]
all is well, happens all the time. Thanks for finding it so fast.
